// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFvht4QVcBlnyXfSqmve5GRB5NBCfhrwE',
    appId: '1:689354934333:web:1d87bf19155423fc588254',
    messagingSenderId: '689354934333',
    projectId: 'blogbox-92168',
    authDomain: 'blogbox-92168.firebaseapp.com',
    databaseURL: 'https://blogbox-92168-default-rtdb.firebaseio.com',
    storageBucket: 'blogbox-92168.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Inh02GtyzZTK2yyQChvrd7YX3L35a-c',
    appId: '1:689354934333:android:cfda6188464782b5588254',
    messagingSenderId: '689354934333',
    projectId: 'blogbox-92168',
    databaseURL: 'https://blogbox-92168-default-rtdb.firebaseio.com',
    storageBucket: 'blogbox-92168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHyCvER5kNJMsUiJi0TqV8K0tNVOowvk',
    appId: '1:689354934333:ios:422232a2fd6d2abd588254',
    messagingSenderId: '689354934333',
    projectId: 'blogbox-92168',
    databaseURL: 'https://blogbox-92168-default-rtdb.firebaseio.com',
    storageBucket: 'blogbox-92168.appspot.com',
    iosClientId: '689354934333-lithmq192gc5vjs01o127pqnfcurj0qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHyCvER5kNJMsUiJi0TqV8K0tNVOowvk',
    appId: '1:689354934333:ios:422232a2fd6d2abd588254',
    messagingSenderId: '689354934333',
    projectId: 'blogbox-92168',
    databaseURL: 'https://blogbox-92168-default-rtdb.firebaseio.com',
    storageBucket: 'blogbox-92168.appspot.com',
    iosClientId: '689354934333-lithmq192gc5vjs01o127pqnfcurj0qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );
}
